feature Added mfa api endpoints to work with oauth2 access_token
hiqdev/yii2-mfa pull request #16
Opened 2021-03-16 08:11 UTC by strorch

2021-03-17 07:58 UTC, tafid approved these changes

2021-03-17 12:06 UTC, SilverFire requested changes

2021-03-17 12:06 UTC, SilverFire commented on src/GrandType/UserCredentials.php
> +namespace hiqdev\yii2\mfa\GrandType;
```suggestion
namespace hiqdev\yii2\mfa\GrantType;
```

2021-03-17 12:06 UTC, SilverFire commented on src/GrandType/UserCredentials.php
> +namespace hiqdev\yii2\mfa\GrandType;
И дальше по коду

2021-03-17 12:06 UTC, SilverFire commented on src/behaviors/OauthLoginBehavior.php
> +        if (empty($identity)) {
```suggestion
        if ($identity === null) {
```

можно?

2021-03-17 12:06 UTC, SilverFire commented on src/behaviors/OauthLoginBehavior.php
> +            $this->response->data['_error'] = 'invalid token';
```suggestion
            $this->response->data = ['_error' => 'invalid_token'];
```

А там `data` изначально массив?

2021-03-17 12:06 UTC, SilverFire commented on src/controllers/TotpController.php
> +    public $enableCsrfValidation = false;
Этот контроллер оперирует данными из сессии. CSRF в нём отключать неуместно.
Почему отключён?

2021-03-17 12:13 UTC, strorch commented on src/controllers/TotpController.php
> +    public $enableCsrfValidation = false;
пост запроси не проходять без Csrf

2021-03-17 12:16 UTC, strorch commented on src/behaviors/OauthLoginBehavior.php
> +        if (empty($identity)) {
да

2021-03-17 14:42 UTC, SilverFire commented on src/controllers/TotpController.php
> +                        'actions' => ['api-temporary-secret', 'api-disable', 'api-enable'],
```suggestion
                        'actions' => ['api-temporary-secret', 'api-disable', 'api-enable'],
                        'roles' => ['@'],
```

Эти методы должны быть доступны только аутентифицированным, нет?

2021-03-24 16:06 UTC, bladeroot approved these changes

2021-03-24 16:06 UTC, bladeroot commented on src/GrandType/UserCredentials.php
> +namespace hiqdev\yii2\mfa\GrandType;
GrantType

2021-03-24 16:06 UTC, bladeroot commented on src/base/TotpSecretStorageInterface.php
> +    public function setTotpSecret(string $secret);
почему нет типа возвращаемых данных?

2021-03-24 16:19 UTC, SilverFire commented on src/GrandType/UserCredentials.php
> +namespace hiqdev\yii2\mfa\GrandType;
Это ты старый коммит прокомментировал

2021-03-24 16:22 UTC, tafid requested changes

2021-03-24 16:22 UTC, tafid commented on src/GrantType/UserCredentials.php
> +    public function validateRequest(RequestInterface $request, ResponseInterface $response)
```suggestion
    public function validateRequest(RequestInterface $request, ResponseInterface $response): bool
```

2021-03-24 16:22 UTC, tafid commented on src/base/ApiMfaIdentityInterface.php
> +    public function setTemporarySecret(?string $secret);
```suggestion
    public function setTemporarySecret(?string $secret): void;
```

2021-03-24 16:22 UTC, tafid commented on src/base/MfaSaveInterface.php
> +    public function save();
```suggestion
    public function save(): void;
```

2021-03-24 16:22 UTC, tafid commented on src/behaviors/OauthLoginBehavior.php
> +        $token = $this->request->post()['access_token'] ?? '';
```suggestion
        $token = $this->request->post('access_token', '');
```

2021-03-24 16:22 UTC, tafid commented on src/controllers/TotpController.php
> +        if (!$this->module->getTotp()->verifyCode($secret, \Yii::$app->request->post()['code'] ?? '')) {
```suggestion
        if (!$this->module->getTotp()->verifyCode($secret, $this->request->post('code', ''))) {
```

2021-03-24 16:40 UTC, bladeroot commented on src/base/MfaSaveInterface.php
> +    public function save();
а не true model->save()

2021-03-26 08:16 UTC, merged