fixed open redirect error in back action
hiqdev/yii2-mfa pull request #17
Opened 2021-04-02 11:29 UTC by strorch

2021-04-02 12:03 UTC, hiqsol requested changes

2021-04-02 12:03 UTC, hiqsol commented on src/controllers/TotpController.php
> +        \Yii::$app->getSession()->remove(self::TOTP_BACK_URL);
добавь плиз `use Yii` не нравятся эти `\`

2021-04-02 13:43 UTC, SilverFire commented
Хм, а как это исправляет open redirect?

`actionDisable()` и `actionEnable()` всё так же принимают произвольный URL

2021-04-02 14:04 UTC, strorch commented
@SilverFire тепер редірект буде робитись через $controller->redirect($url) а він це діло провалідує, і крім опенредіректа там ще  xss був

2021-04-07 12:43 UTC, hiqsol approved these changes

2021-04-07 12:43 UTC, merged